language: cpp

cache:
  directories:
    - "~/.platformio"

jobs:
  include:
    - name: "Dashboard Firmware"
      install:
        - pip install --user -U platformio
      script:
        - cd dashboard/firmware/
        - platformio run
    - name: "Dashboard Firmware Tests"
      script:
        - cd dashboard/firmware/tests/
        - ./build.sh
        - cd build
        - ctest -V
