language: python

python:
  - '3.7'

before_install:
  - sudo add-apt-repository -y ppa:openscad/releases
  - sudo apt-get update
  - sudo apt-get install -y openscad tree
  - pip install platformio

install:
  - pip install -r cad/requirements.txt

script:
  - ./build_and_test.sh
