language: python

python:
  - '3.6'

before_install:
  - sudo add-apt-repository -y ppa:openscad/releases
  - sudo apt-get update
  - sudo apt-get install -y openscad

install:
  - pip install -r requirements.txt

script:
  - pytest --verbose
